<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

# Laboratorio API's 

SetMagic Productions es una empresa especializada en la provisión de servicios integrales para la realización de rodajes cinematográficos y audiovisuales. Nos dedicamos a facilitar tanto el atrezzo necesario para las producciones como los lugares idóneos para llevar a cabo los rodajes, ya sea en entornos al aire libre o en interiores.

**Servicios Ofrecidos:**

- **Atrezzo Creativo:** Contamos con un extenso catálogo de atrezzo que abarca desde accesorios hasta muebles y objetos temáticos para ambientar cualquier tipo de  escena.

- **Locaciones Únicas:** Nuestra empresa ofrece una amplia selección de locaciones, que incluyen desde escenarios naturales como playas, bosques y montañas, hasta espacios interiores como estudios, casas históricas y edificios emblemáticos.

- **Servicios de Producción:** Además de proporcionar atrezzo y locaciones, también ofrecemos servicios de producción audiovisual, incluyendo equipos de filmación, personal técnico y servicios de postproducción.

**Herramientas y Tecnologías:**

Para recopilar información sobre nuevas locaciones y tendencias en atrezzo, utilizamos herramientas de web scraping como Beautiful Soup y Selenium para extraer datos de sitios web relevantes y redes sociales especializadas en cine y producción audiovisual. También integramos APIs de plataformas de alquiler de locaciones y bases de datos de atrezzo para acceder a información actualizada y detallada.

**Almacenamiento de Datos:**

La información recopilada mediante web scraping y APIs se almacena en una base de datos no relacional MongoDB. Esta base de datos nos permite organizar eficientemente la información sobre locaciones, atrezzo, clientes y proyectos en curso, facilitando su acceso y gestión.

**Objetivo:**

Nuestro objetivo principal es proporcionar a nuestros clientes una experiencia fluida y personalizada en la búsqueda y selección de locaciones y atrezzo para sus proyectos audiovisuales. Utilizando tecnologías avanzadas y una amplia red de contactos en la industria, nos esforzamos por ofrecer soluciones creativas y de alta calidad que satisfagan las necesidades específicas de cada producción.


# Lab: APIs y Obtención de Datos de Localizaciones para Rodajes

En este laboratorio aprenderás a utilizar APIs para obtener información sobre localizaciones de rodaje en la Comunidad de Madrid. A lo largo de este ejercicio, implementarás funciones que te permitirán extraer coordenadas, buscar lugares de interés y almacenar la información en un formato que puedas reutilizar.

## Objetivo

Obtener información geográfica y sobre posibles localizaciones para rodajes en diferentes municipios de la Comunidad de Madrid, utilizando APIs como **Geopy** y **Foursquare**.

### Paso 1: Obtener Coordenadas de los Municipios

Primero, necesitas obtener las coordenadas geográficas (latitud y longitud) de cada municipio en la Comunidad de Madrid. Para esto, utilizarás la biblioteca **Geopy** y su funcionalidad para geocodificar. La lista de los municipios de la Comunidad de Madrid es:

```python
lista_municipios = ['acebeda-la', 'ajalvir', 'alameda-del-valle', 'alamo-el', 'alcala-de-henares', 'alcobendas', 'alcorcon', 'aldea-del-fresno', 'algete', 'alpedrete', 'ambite', 'anchuelo', 'aranjuez', 'arganda-del-rey', 'arroyomolinos', 'atazar-el', 'batres', 'becerril-de-la-sierra', 'belmonte-de-tajo', 'berrueco-el', 'berzosa-del-lozoya', 'boadilla-del-monte', 'boalo-el', 'braojos', 'brea-de-tajo', 'brunete', 'buitrago-del-lozoya', 'bustarviejo', 'cabanillas-de-la-sierra', 'cabrera-la', 'cadalso-de-los-vidrios', 'camarma-de-esteruelas', 'campo-real', 'canencia', 'carabana', 'casarrubuelos', 'cenicientos', 'cercedilla', 'cervera-de-buitrago', 'chapineria', 'chinchon', 'ciempozuelos', 'cobena', 'collado-mediano', 'collado-villalba', 'colmenar-del-arroyo', 'colmenar-de-oreja', 'colmenarejo', 'colmenar-viejo', 'corpa', 'coslada', 'cubas-de-la-sagra', 'daganzo-de-arriba', 'escorial-el', 'estremera', 'fresnedillas-de-la-oliva', 'fresno-de-torote', 'fuenlabrada', 'fuente-el-saz-de-jarama', 'fuentiduena-de-tajo', 'galapagar', 'garganta-de-los-montes', 'gargantilla-del-lozoya-y-pinilla-de-buitrago', 'gascones', 'getafe', 'grinon', 'guadalix-de-la-sierra', 'guadarrama', 'hiruela-la', 'horcajo-de-la-sierra-aoslos', 'horcajuelo-de-la-sierra', 'hoyo-de-manzanares', 'humanes-de-madrid', 'leganes', 'loeches', 'lozoya', 'lozoyuela-navas-sieteiglesias', 'madarcos', 'madrid', 'majadahonda', 'manzanares-el-real', 'meco', 'mejorada-del-campo', 'miraflores-de-la-sierra', 'molar-el', 'molinos-los', 'montejo-de-la-sierra', 'moraleja-de-enmedio', 'moralzarzal', 'morata-de-tajuna', 'mostoles', 'navacerrada', 'navalafuente', 'navalagamella', 'navalcarnero', 'navarredonda-y-san-mames', 'navas-del-rey', 'nuevo-baztan', 'olmeda-de-las-fuentes', 'orusco-de-tajuna', 'paracuellos-de-jarama', 'parla', 'patones', 'pedrezuela', 'pelayos-de-la-presa', 'perales-de-tajuna', 'pezuela-de-las-torres', 'pinilla-del-valle', 'pinto', 'pinuecar-gandullas', 'pozuelo-de-alarcon', 'pozuelo-del-rey', 'pradena-del-rincon', 'puebla-de-la-sierra', 'puentes-viejas-manjiron', 'quijorna', 'rascafria', 'reduena', 'ribatejada', 'rivas-vaciamadrid', 'robledillo-de-la-jara', 'robledo-de-chavela', 'robregordo', 'rozas-de-madrid-las', 'rozas-de-puerto-real', 'san-agustin-del-guadalix', 'san-fernando-de-henares', 'san-lorenzo-de-el-escorial', 'san-martin-de-la-vega', 'san-martin-de-valdeiglesias', 'san-sebastian-de-los-reyes', 'santa-maria-de-la-alameda', 'santorcaz', 'santos-de-la-humosa-los', 'serna-del-monte-la', 'serranillos-del-valle', 'sevilla-la-nueva', 'somosierra', 'soto-del-real', 'talamanca-de-jarama', 'tielmes', 'titulcia', 'torrejon-de-ardoz', 'torrejon-de-la-calzada', 'torrejon-de-velasco', 'torrelaguna', 'torrelodones', 'torremocha-de-jarama', 'torres-de-la-alameda', 'tres-cantos', 'valdaracete', 'valdeavero', 'valdelaguna', 'valdemanco', 'valdemaqueda', 'valdemorillo', 'valdemoro', 'valdeolmos-alalpardo', 'valdepielagos', 'valdetorres-de-jarama', 'valdilecha', 'valverde-de-alcala', 'velilla-de-san-antonio', 'vellon-el', 'venturada', 'villaconejos', 'villa-del-prado', 'villalbilla', 'villamanrique-de-tajo', 'villamanta', 'villamantilla', 'villanueva-de-la-canada', 'villanueva-del-pardillo', 'villanueva-de-perales', 'villar-del-olmo', 'villarejo-de-salvanes', 'villaviciosa-de-odon', 'villavieja-del-lozoya', 'zarzalejo']
```

1. Instalar y configurar la biblioteca de Geopy para realizar la geocodificación.

2. Crear una función que reciba una lista de municipios y devuelva un DataFrame con los nombres de los municipios y sus respectivas coordenadas (latitud y longitud).

3. Validar los datos obtenidos para verificar si hay municipios sin coordenadas y resolver posibles problemas, como nombres incorrectos o faltantes.


### Paso 2: Buscar Localizaciones Relevantes con la API de Foursquare

Una vez obtenidas las coordenadas de los municipios, utilizarás la API de Foursquare para buscar servicios que pueden ser importantes en un rodaje (ej: parques, edificios históricos, plazas).

En este punto es importante que reflexiones sobre los servicios o establecimientos clave que considerarías relevantes para establecer una empresa de servicios para rodajes. No hay una única respuesta correcta, ya que depende de la estrategia y visión que tengas. Al menos deberás elegir 5 tipos de servicios que puedan influir en la decisión de ubicación. Ejemplos de estos servicios pueden incluir:

- Parques o áreas verdes para rodajes exteriores.

- Centros comerciales que faciliten acceso a diferentes necesidades logísticas.

- Bares o restaurantes para el catering del equipo.

- Tiendas especializadas en disfraces o vestuario.

- Alquileres de equipos audiovisuales.

Es crucial entender que esta selección depende de la naturaleza y enfoque de la empresa. Tal vez para algunos proyectos sea más importante estar cerca de áreas residenciales o lugares con buena conexión de transporte. Otros proyectos podrían priorizar la proximidad a tiendas especializadas o servicios de entretenimiento. Es vuestra decisión! 

1. Crear una cuenta en [Foursquare](https://location.foursquare.com/developer/) y obtener la API Key necesaria para realizar las solicitudes. Leer la documentación para entender como funciona. 

2. Definir una función para realizar búsquedas de lugares cercanos a las coordenadas de cada municipio. Esta función debe permitir filtrar los resultados por categoría y distancia.

3. Explorar las categorías disponibles en Foursquare y seleccionar aquellas que se ajusten a los servicios clave que decidáis para vuestra estrategia.

4. Aplicar la función de búsqueda a cada municipio, recopilando información sobre los lugares relevantes.

Recuerda que la elección de categorías es un punto de análisis clave en este ejercicio, ya que la información que obtendréis será fundamental para decidir la ubicación ideal para vuestra empresa. Aseguraos de justificar vuestras decisiones y considerar diferentes perspectivas. Para cada una de los municipios deberás sacar la información de todos los servicios elegidos. 

### Paso 3: Limpieza de la Información

La información obtenida de Foursquare puede incluir muchos detalles innecesarios. Tu objetivo es quedarte únicamente con los campos relevantes para tu análisis (nombre, dirección, coordenadas, tipo de lugar, etc.).


1. Explorar la estructura de los datos obtenidos para identificar los campos importantes y limpiar la información.

2. Eliminar duplicados y valores nulos para garantizar la consistencia y calidad de los datos.

### Paso 4: Almacenamiento de los Datos

Una vez que tengas la información limpia y organizada, almacénala en un archivo CSV que puedas reutilizar en futuros análisis.

1. Instalar y configurar la biblioteca de Geopy para realizar la geocodificación.

In [98]:
import requests
import pandas as pd
from geopy.geocoders import Nominatim

2. Crear una función que reciba una lista de municipios y devuelva un DataFrame con los nombres de los municipios y sus respectivas coordenadas (latitud y longitud).

In [99]:
geolocator = Nominatim(user_agent="api-locaciones")

# Función para obtener las coordenadas de un municipio
def obtenercoordenadas(municipio):
    location = geolocator.geocode(municipio)
    if location:
        return (municipio, location.latitude, location.longitude)
    else:
        print(f"No se encontraron coordenadas para {municipio}")
        return None

In [100]:
lista_municipios = ['acebeda-la', 'ajalvir', 'alameda-del-valle', 'alamo-el', 'alcala-de-henares', 'alcobendas', 'alcorcon', 'aldea-del-fresno', 'algete', 'alpedrete',
                    'ambite', 'anchuelo', 'aranjuez', 'arganda-del-rey', 'arroyomolinos', 'atazar-el', 'batres', 'becerril-de-la-sierra', 'belmonte-de-tajo', 'berrueco-el',
                    'berzosa-del-lozoya', 'boadilla-del-monte', 'boalo-el', 'braojos', 'brea-de-tajo', 'brunete', 'buitrago-del-lozoya', 'bustarviejo',
                    'cabanillas-de-la-sierra', 'cabrera-la', 'cadalso-de-los-vidrios', 'camarma-de-esteruelas', 'campo-real', 'canencia', 'carabana', 'casarrubuelos',
                    'cenicientos', 'cercedilla', 'cervera-de-buitrago', 'chapineria', 'chinchon', 'ciempozuelos', 'cobena', 'collado-mediano', 'collado-villalba',
                    'colmenar-del-arroyo', 'colmenar-de-oreja', 'colmenarejo', 'colmenar-viejo', 'corpa', 'coslada', 'cubas-de-la-sagra', 'daganzo-de-arriba',
                    'escorial-el', 'estremera', 'fresnedillas-de-la-oliva', 'fresno-de-torote', 'fuenlabrada', 'fuente-el-saz-de-jarama', 'fuentiduena-de-tajo',
                    'galapagar', 'garganta-de-los-montes', 'gargantilla-del-lozoya-y-pinilla-de-buitrago', 'gascones', 'getafe', 'grinon', 'guadalix-de-la-sierra',
                    'guadarrama', 'hiruela-la', 'horcajo-de-la-sierra-aoslos', 'horcajuelo-de-la-sierra', 'hoyo-de-manzanares', 'humanes-de-madrid', 'leganes',
                    'loeches', 'lozoya', 'lozoyuela-navas-sieteiglesias', 'madarcos', 'madrid', 'majadahonda', 'manzanares-el-real', 'meco',
                    'mejorada-del-campo', 'miraflores-de-la-sierra', 'molar-el', 'molinos-los', 'montejo-de-la-sierra', 'moraleja-de-enmedio', 'moralzarzal', 
                    'morata-de-tajuna', 'mostoles', 'navacerrada', 'navalafuente', 'navalagamella', 'navalcarnero', 'navarredonda-y-san-mames', 'navas-del-rey', 
                    'nuevo-baztan', 'olmeda-de-las-fuentes', 'orusco-de-tajuna', 'paracuellos-de-jarama', 'parla', 'patones', 'pedrezuela', 'pelayos-de-la-presa',
                    'perales-de-tajuna', 'pezuela-de-las-torres', 'pinilla-del-valle', 'pinto', 'pinuecar-gandullas', 'pozuelo-de-alarcon', 'pozuelo-del-rey', 
                    'pradena-del-rincon', 'puebla-de-la-sierra', 'puentes-viejas-manjiron', 'quijorna', 'rascafria', 'reduena', 'ribatejada', 'rivas-vaciamadrid', 
                    'robledillo-de-la-jara', 'robledo-de-chavela', 'robregordo', 'rozas-de-madrid-las', 'rozas-de-puerto-real', 'san-agustin-del-guadalix', 
                    'san-fernando-de-henares', 'san-lorenzo-de-el-escorial', 'san-martin-de-la-vega', 'san-martin-de-valdeiglesias', 'san-sebastian-de-los-reyes', 
                    'santa-maria-de-la-alameda', 'santorcaz', 'santos-de-la-humosa-los', 'serna-del-monte-la', 'serranillos-del-valle', 'sevilla-la-nueva', 'somosierra', 
                    'soto-del-real', 'talamanca-de-jarama', 'tielmes', 'titulcia', 'torrejon-de-ardoz', 'torrejon-de-la-calzada', 'torrejon-de-velasco', 'torrelaguna', 
                    'torrelodones', 'torremocha-de-jarama', 'torres-de-la-alameda', 'tres-cantos', 'valdaracete', 'valdeavero', 'valdelaguna', 'valdemanco', 'valdemaqueda', 
                    'valdemorillo', 'valdemoro', 'valdeolmos-alalpardo', 'valdepielagos', 'valdetorres-de-jarama', 'valdilecha', 'valverde-de-alcala', 'velilla-de-san-antonio', 
                    'vellon-el', 'venturada', 'villaconejos', 'villa-del-prado', 'villalbilla', 'villamanrique-de-tajo', 'villamanta', 'villamantilla', 'villanueva-de-la-canada', 
                    'villanueva-del-pardillo', 'villanueva-de-perales', 'villar-del-olmo', 'villarejo-de-salvanes', 'villaviciosa-de-odon', 'villavieja-del-lozoya', 'zarzalejo']

In [101]:
lista_municipios1 = ['acebeda-la', 'ajalvir', 'alameda-del-valle', 'alamo-el', 'alcala-de-henares', 'alcobendas', 'alcorcon', 'aldea-del-fresno', 'algete', 'alpedrete']

In [102]:
obtenercoordenadas('alcala-de-henares')

('alcala-de-henares', 40.4818396, -3.3644973)

In [103]:
def obtenercoordenadaslista(lista):
    listacoordenadas=[]
    for unidad in lista:
        i=obtenercoordenadas(unidad)
        listacoordenadas.append(i)
    return pd.DataFrame(listacoordenadas)

In [104]:
df_municipios=obtenercoordenadaslista(lista_municipios)

In [105]:
df_municipios

                         0          1         2
0               acebeda-la  41.086958 -3.624399
1                  ajalvir  40.534230 -3.480782
2        alameda-del-valle  40.917718 -3.843822
3                 alamo-el  40.230730 -3.990589
4        alcala-de-henares  40.481840 -3.364497
..                     ...        ...       ...
174        villar-del-olmo  40.336447 -3.235562
175  villarejo-de-salvanes  40.168358 -3.273876
176   villaviciosa-de-odon  40.357379 -3.900233
177  villavieja-del-lozoya  41.006362 -3.671629
178              zarzalejo  40.539281 -4.162484

[179 rows x 3 columns]

In [217]:
df_municipios1=obtenercoordenadaslista(lista_municipios1)

In [218]:
df_municipios1

                   0          1         2
0         acebeda-la  41.086958 -3.624399
1            ajalvir  40.534230 -3.480782
2  alameda-del-valle  40.917718 -3.843822
3           alamo-el  40.230730 -3.990589
4  alcala-de-henares  40.481840 -3.364497
5         alcobendas  40.540008 -3.635849
6           alcorcon  40.349300 -3.828429
7   aldea-del-fresno  40.321521 -4.199360
8             algete  40.596165 -3.497425
9          alpedrete  40.659900 -4.025122

In [106]:
diccionario_df={0:'municipio',
                1:'latitud',
                2:'longitud'
                }

In [107]:
df_municipios=df_municipios.rename(columns=diccionario_df)
df_municipios

                 municipio    latitud  longitud
0               acebeda-la  41.086958 -3.624399
1                  ajalvir  40.534230 -3.480782
2        alameda-del-valle  40.917718 -3.843822
3                 alamo-el  40.230730 -3.990589
4        alcala-de-henares  40.481840 -3.364497
..                     ...        ...       ...
174        villar-del-olmo  40.336447 -3.235562
175  villarejo-de-salvanes  40.168358 -3.273876
176   villaviciosa-de-odon  40.357379 -3.900233
177  villavieja-del-lozoya  41.006362 -3.671629
178              zarzalejo  40.539281 -4.162484

[179 rows x 3 columns]

In [219]:
df_municipios1=df_municipios1.rename(columns=diccionario_df)
df_municipios1

           municipio    latitud  longitud
0         acebeda-la  41.086958 -3.624399
1            ajalvir  40.534230 -3.480782
2  alameda-del-valle  40.917718 -3.843822
3           alamo-el  40.230730 -3.990589
4  alcala-de-henares  40.481840 -3.364497
5         alcobendas  40.540008 -3.635849
6           alcorcon  40.349300 -3.828429
7   aldea-del-fresno  40.321521 -4.199360
8             algete  40.596165 -3.497425
9          alpedrete  40.659900 -4.025122

3. Validar los datos obtenidos para verificar si hay municipios sin coordenadas y resolver posibles problemas, como nombres incorrectos o faltantes.

In [108]:
nulos1=df_municipios['latitud'].isnull()
nulos1.unique()

array([False])

In [109]:
nulos2=df_municipios['longitud'].isnull()
nulos2.unique()

array([False])

In [110]:
df_municipios['latitud'].duplicated().unique()

array([False])

In [111]:
df_municipios['longitud'].duplicated().unique()

array([False])

In [112]:
df_municipios['longitud'].duplicated().unique()

array([False])

In [117]:
df_municipios['municipio']=df_municipios['municipio'].replace(r"-"," ", regex=True).str.capitalize()

In [220]:
df_municipios1['municipio']=df_municipios1['municipio'].replace(r"-"," ", regex=True).str.capitalize()

In [118]:
df_municipios

                 municipio    latitud  longitud
0               Acebeda la  41.086958 -3.624399
1                  Ajalvir  40.534230 -3.480782
2        Alameda del valle  40.917718 -3.843822
3                 Alamo el  40.230730 -3.990589
4        Alcala de henares  40.481840 -3.364497
..                     ...        ...       ...
174        Villar del olmo  40.336447 -3.235562
175  Villarejo de salvanes  40.168358 -3.273876
176   Villaviciosa de odon  40.357379 -3.900233
177  Villavieja del lozoya  41.006362 -3.671629
178              Zarzalejo  40.539281 -4.162484

[179 rows x 3 columns]

In [124]:
def mover_articulo(texto):
    palabras = texto.split()
    if palabras[-1].lower() in ['el', 'la', 'los', 'las']: 
        articulo = palabras.pop()  
        return f"{articulo} {' '.join(palabras)}"  
    return texto  

df_municipios['municipio']=df_municipios['municipio'].apply(mover_articulo).str.capitalize()

In [221]:
df_municipios1['municipio']=df_municipios1['municipio'].apply(mover_articulo).str.capitalize()

In [222]:
df_municipios1

           municipio    latitud  longitud
0         La acebeda  41.086958 -3.624399
1            Ajalvir  40.534230 -3.480782
2  Alameda del valle  40.917718 -3.843822
3           El alamo  40.230730 -3.990589
4  Alcala de henares  40.481840 -3.364497
5         Alcobendas  40.540008 -3.635849
6           Alcorcon  40.349300 -3.828429
7   Aldea del fresno  40.321521 -4.199360
8             Algete  40.596165 -3.497425
9          Alpedrete  40.659900 -4.025122

In [135]:
df_municipios.to_csv('lista_de_municipios.csv')

In [137]:
df_municipios=pd.read_csv('lista_de_municipios.csv')

1. Crear una cuenta en [Foursquare](https://location.foursquare.com/developer/) y obtener la API Key necesaria para realizar las solicitudes. Leer la documentación para entender como funciona.

Creada

2. Definir una función para realizar búsquedas de lugares cercanos a las coordenadas de cada municipio. Esta función debe permitir filtrar los resultados por categoría y distancia.

In [138]:
API_KEY='fsq3SzWy/v5/gByWN6kgYdWZHVFwYrUVvkA/x70h6tI4NzQ='

In [209]:
def buscar_lugares(latitud,longitud, categoria, radio):
    url = "https://api.foursquare.com/v3/places/search"
    headers = {
        "accept": "application/json",
        "Authorization": f"{API_KEY}" 
    }
    
    params = {
        "ll": f"{latitud},{longitud}",  # Coordenadas
        "radius": radio,  
        "categories": categoria,
        "limit": 50,
        "fields":'name,distance,location'
    }
    
    response = requests.get(url, headers=headers, params=params)
    return response.json()

In [238]:
def buscar_lugares_por_municipios(df_municipios, categoria, radio):
    url = "https://api.foursquare.com/v3/places/search"
    headers = {
        "accept": "application/json",
        "Authorization": f"{API_KEY}"  # Pasar la API key como argumento
    }
    
    # Lista para almacenar los resultados de cada municipio


    # Iterar sobre el DataFrame de municipios
    for idx, row in df_municipios.iterrows():
        latitud = row['latitud']
        longitud = row['longitud']
        municipio = row['municipio']
        
        params = {
            "ll": f"{latitud},{longitud}",  # Coordenadas
            "radius": radio,  
            "categories": categoria,
            "limit": 50,  #
            "fields": 'name,distance,location,geocodes'
        }

        response = requests.get(url, headers=headers, params=params)

        data = response.json()
        
        resultados = []

        lugares = data.get('results', [])

        for lugar in lugares:
            nombre = lugar.get('name')
            distancia = lugar.get('distance')
            location=lugar.get('location')
            geocodes= lugar.get('geocodes')

            resultados.append({
                    'Municipio': municipio,
                    'Latitud': latitud,
                    'Longitud': longitud,
                    'Nombre del Lugar': nombre,
                    'Distancia (m)': distancia,
                    'Location':location,
                    'Geocodes': geocodes

                })

    df_resultados = pd.DataFrame(resultados)
    
    return df_resultados

In [239]:
lugares=buscar_lugares_por_municipios(df_municipios1,13065,3000)
lugares

,Municipio,Latitud,Longitud,Nombre del Lugar,Distancia (m),Location,Geocodes
0,Alpedrete,40.6599,-4.025122,La Tabernita del Mimo,81,"{'address': 'Plaza Vicente Guillen Zamorano, 2...","{'drop_off': {'latitude': 40.659733, 'longitud..."
1,Alpedrete,40.6599,-4.025122,El Gallinero,2317,"{'address': 'Carretera de Navacerrada, Km 0,6'...","{'main': {'latitude': 40.64427, 'longitude': -..."
2,Alpedrete,40.6599,-4.025122,Pizza Hut,2566,"{'address': 'Avenida Juan Carlos I, 46', 'admi...","{'main': {'latitude': 40.637461, 'longitude': ..."
3,Alpedrete,40.6599,-4.025122,Maná,15,"{'address': 'Calle de la Constitución, 2', 'ad...","{'drop_off': {'latitude': 40.659832, 'longitud..."
4,Alpedrete,40.6599,-4.025122,Restaurante Maná,26,"{'address': 'Plaza de la Constitución, 1', 'ad...","{'drop_off': {'latitude': 40.659875, 'longitud..."
5,Alpedrete,40.6599,-4.025122,El Pollo Dorado II,53,"{'address': 'Plaza de la Constitución, 1', 'ad...","{'drop_off': {'latitude': 40.659869, 'longitud..."
6,Alpedrete,40.6599,-4.025122,El Cabrero,59,"{'address': 'Calle de San Juan, 10', 'admin_re...","{'drop_off': {'latitude': 40.659491, 'longitud..."
7,Alpedrete,40.6599,-4.025122,Kekema,82,"{'address': 'Pasaje de la Pozuela, 2', 'admin_...","{'main': {'latitude': 40.659645, 'longitude': ..."
8,Alpedrete,40.6599,-4.025122,Sabor Bohemio,99,"{'address': 'Avenida de los Canteros, 14', 'ad...","{'drop_off': {'latitude': 40.659862, 'longitud..."
9,Alpedrete,40.6599,-4.025122,McDonald's,176,"{'address': 'Sbda. Juan Carlos I, 46', 'admin_...","{'main': {'latitude': 40.658747, 'longitude': ..."
10,Alpedrete,40.6599,-4.025122,Restaurante Bar el 42,2000,"{'address': 'Carretera de la Coruña, Km 42', '...","{'main': {'latitude': 40.64419, 'longitude': -..."
11,Alpedrete,40.6599,-4.025122,El Rincon de Boni,266,"{'address': 'Dr. Varela, 7', 'admin_region': '...","{'main': {'latitude': 40.657828, 'longitude': ..."
12,Alpedrete,40.6599,-4.025122,Canteros 31,564,"{'address': 'Avenida de los Canteros, 31', 'ad...","{'main': {'latitude': 40.65904, 'longitude': -..."
13,Alpedrete,40.6599,-4.025122,Ginos Planetocio Villalba,2615,"{'address': 'Calle Central, 46', 'admin_region...","{'main': {'latitude': 40.638168, 'longitude': ..."
14,Alpedrete,40.6599,-4.025122,Restaurante Escala,1257,"{'address': 'Calle San Jose, 12', 'admin_regio...","{'drop_off': {'latitude': 40.659748, 'longitud..."
15,Alpedrete,40.6599,-4.025122,Deshollinadores de Madrid,1398,"{'address': 'Calle Monte Redondo, 12', 'admin_...","{'drop_off': {'latitude': 40.648528, 'longitud..."
16,Alpedrete,40.6599,-4.025122,Rte. las Canteras,1639,"{'address': 'Carretera M-601, Km 3.600', 'admi...","{'main': {'latitude': 40.669018, 'longitude': ..."
17,Alpedrete,40.6599,-4.025122,VIPS Planetocio Villalba,2514,"{'address': 'Avenida Juan Carlos I, 46', 'admi...","{'main': {'latitude': 40.637879, 'longitude': ..."
18,Alpedrete,40.6599,-4.025122,Kyoto,2720,"{'address': 'Costa Verde, 1', 'admin_region': ...","{'drop_off': {'latitude': 40.636202, 'longitud..."
19,Alpedrete,40.6599,-4.025122,La Sureña,2557,"{'address': 'Avenida de Juan Carlos I, 46', 'a...","{'main': {'latitude': 40.637575, 'longitude': ..."
20,Alpedrete,40.6599,-4.025122,McDonald's,2544,"{'address': 'Calle Avellano, 2', 'admin_region...","{'drop_off': {'latitude': 40.637693, 'longitud..."
21,Alpedrete,40.6599,-4.025122,Burger King,2891,"{'address': 'Calle Cañada Real, s/n', 'admin_r...","{'main': {'latitude': 40.63537, 'longitude': -..."
22,Alpedrete,40.6599,-4.025122,Área de Servicio Villalba - Como,2136,"{'address': 'Autopista Ap-6, Km 42', 'admin_re...","{'main': {'latitude': 40.644109, 'longitude': ..."
23,Alpedrete,40.6599,-4.025122,Área de Servicio Villalba - Como,2138,"{'address': 'Autopista Ap-6, Km 42', 'admin_re...","{'main': {'latitude': 40.644051, 'longitude': ..."
24,Alpedrete,40.6599,-4.025122,Market,2159,"{'address': 'Autovía A-6M', 'admin_region': 'C...","{'main': {'latitude': 40.64401, 'longitude': -..."
25,Alpedrete,40.6599,-4.025122,Pizzamore,2387,"{'address': 'Avenida Reina Victoria, 26', 'adm...","{'main': {'latitude': 40.638484, 'longitude': ..."
26,Alpedrete,40.6599,-4.025122,Foster's Hollywood Planetocio,2494,"{'address': 'Avenida Juan Carlos 1º', 'admin_r...","{'main': {'latitude': 40.638031, 'longitude': ..."
27,Alpedrete,40.6599,-4.025122,Tasty Poke Bar,2587,"{'address': 'Calle Central, 46', 'address_exte...","{'main': {'latitude': 40.637333, 'longitude': ..."
28,Alpedrete,40.6599,-4.025122,Don G,2609,"{'address': 'Calle Central, 46', 'admin_region...","{'drop_off': {'latitude': 40.636261, 'longitud..."
29,Alpedrete,40.6599,-4.025122,La Pulpería,2706,"{'address': 'Calle Costa Verde, 2', 'address_e...","{'drop_off': {'latitude': 40.636048, 'longitud..."
30,Alpedrete,40.6599,-4.025122,Wok-asiatico,2782,"{'address': 'Calle Rincón de las Heras, 2', 'a...","{'drop_off': {'latitude': 40.638274, 'longitud..."
31,Alpedrete,40.6599,-4.025122,Jamaica,2963,"{'address': 'Calle Rincón de las Heras, 1', 'a...","{'main': {'latitude': 40.636256, 'longitude': ..."
32,Alpedrete,40.6599,-4.025122,Agarimo,3103,"{'address': 'Juan Carlos I, 45', 'admin_region...","{'drop_off': {'latitude': 40.636223, 'longitud..."
33,Alpedrete,40.6599,-4.025122,Cafe Viena Restaurante,100,"{'address': 'Calle Real, 10', 'admin_region': ...","{'main': {'latitude': 40.659768, 'longitude': ..."
34,Alpedrete,40.6599,-4.025122,Club Social Deportivo los Berrocales,1499,"{'address': 'Calle de las Aguas, 39', 'admin_r...","{'drop_off': {'latitude': 40.653822, 'longitud..."
35,Alpedrete,40.6599,-4.025122,Churreria Santa Quiteria,2393,"{'address': 'Calle Primavera, 94', 'admin_regi...","{'main': {'latitude': 40.653126, 'longitude': ..."
36,Alpedrete,40.6599,-4.025122,La Ermita de los Negrales,2517,"{'address': 'Santa Emilia, 4B', 'admin_region'...","{'main': {'latitude': 40.637306, 'longitude': ..."
37,Alpedrete,40.6599,-4.025122,Restaurante Pizza Jardin,2544,"{'address': 'Calle del Avellano, s/n', 'admin_...","{'main': {'latitude': 40.637445, 'longitude': ..."
38,Alpedrete,40.6599,-4.025122,Vips,2594,"{'address': 'Avenida Juan Carlos I, 46', 'admi...","{'main': {'latitude': 40.637295, 'longitude': ..."
39,Alpedrete,40.6599,-4.025122,Gambrinus,2827,"{'address': 'Rcón. Heras, s/n', 'admin_region'...","{'main': {'latitude': 40.638036, 'longitude': ..."

In [ ]:
lugares=buscar_lugares_por_municipios(df_municipios,13065,1000)
lugares

In [230]:
lugares=buscar_lugares(40.336447,-3.235562, 13065, 5000)
lugares

{'results': [{'distance': 476,
   'location': {'address': 'Avenida de la Estación, 106',
    'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'cross_street': '',
    'formatted_address': 'Avenida de la Estación, 106, 28293 Zarzalejo Comunidad de Madrid',
    'locality': 'Zarzalejo',
    'postcode': '28293',
    'region': 'Comunidad de Madrid'},
   'name': 'La Higuera'},
  {'distance': 4648,
   'location': {'address': 'Carretera Robledo de Chavela, s/n',
    'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'cross_street': 'Salida 47, A6',
    'formatted_address': 'Carretera Robledo de Chavela, s/n (Salida 47, A6), 28200 El Escorial Comunidad de Madrid',
    'locality': 'El Escorial',
    'postcode': '28200',
    'region': 'Comunidad de Madrid'},
   'name': 'Real Club de Golf la Herreria'},
  {'distance': 3156,
   'location': {'address': 'Calle de Díaz Galarza, 8',
    'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'cross_street': '',
    'formatted_address': 'Calle de Díaz Galarza, 8, 28211 Casavieja Madrid',
    'locality': 'Casavieja',
    'postcode': '28211',
    'region': 'Madrid'},
   'name': 'Restaurante Casavieja'},
  {'distance': 68,
   'location': {'address': 'Avenida de la Estacion, 65',
    'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'formatted_address': 'Avenida de la Estacion, 65, 28293 Zarzalejo Comunidad de Madrid',
    'locality': 'Zarzalejo',
    'postcode': '28293',
    'region': 'Comunidad de Madrid'},
   'name': 'Hotel Duque'},
  {'distance': 117,
   'location': {'address': 'Plaza del Llano del Soldado, 9',
    'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'formatted_address': 'Plaza del Llano del Soldado, 9, 28293 Zarzalejo Comunidad de Madrid',
    'locality': 'Zarzalejo',
    'postcode': '28293',
    'region': 'Comunidad de Madrid'},
   'name': 'El Roble'},
  {'distance': 309,
   'location': {'address': 'Avenida Estación, 37',
    'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'cross_street': '',
    'formatted_address': 'Avenida Estación, 37, 28293 Zarzalejo Comunidad de Madrid',
    'locality': 'Zarzalejo',
    'postcode': '28293',
    'region': 'Comunidad de Madrid'},
   'name': 'Bar los Alamos'},
  {'distance': 474,
   'location': {'address': 'Carretera Madrid-Ávila, Km 36',
    'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'formatted_address': 'Carretera Madrid-Ávila, Km 36, 28200 El Escorial Comunidad de Madrid',
    'locality': 'El Escorial',
    'postcode': '28200',
    'region': 'Comunidad de Madrid'},
   'name': 'Asador Cruz Verde'},
  {'distance': 1772,
   'location': {'address': 'Calle del Venero, 6',
    'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'cross_street': '',
    'formatted_address': 'Calle del Venero, 6, 28293 Zarzalejo Comunidad de Madrid',
    'locality': 'Zarzalejo',
    'postcode': '28293',
    'region': 'Comunidad de Madrid'},
   'name': 'Coté Café'},
  {'distance': 1845,
   'location': {'address': 'Plaza Constitución, 2',
    'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'cross_street': '',
    'formatted_address': 'Plaza Constitución, 2, 28293 Zarzalejo Comunidad de Madrid',
    'locality': 'Zarzalejo',
    'postcode': '28293',
    'region': 'Comunidad de Madrid'},
   'name': 'Restaurante la Posada'},
  {'distance': 3211,
   'location': {'address': 'Galarza, s/n',
    'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'formatted_address': 'Galarza, s/n, 28211 El Escorial Madrid',
    'locality': 'El Escorial',
    'postcode': '28211',
    'region': 'Madrid'},
   'name': 'Los Candiles'},
  {'distance': 3295,
   'location': {'admin_region': 'Comunidad de Madrid',
    'country': 'ES',
    'formatted_address': 'San Lorenzo de el Escorial Madrid',
    'locality': 'San Lorenzo de el Escorial',
    'region': 'Madrid'},
   'name': 'La Silla de Felipe II'}],
 'context': {'geo_bounds': {'circle': {'center': {'latitude': 40.5392812,
     'longitude': -4.1624845},
    'radius': 5000}}}}

3. Explorar las categorías disponibles en Foursquare y seleccionar aquellas que se ajusten a los servicios clave que decidáis para vuestra estrategia.

In [ ]:
11056	Business and Professional Services > Food and Beverage Service
11124	Business and Professional Services > Office
13065	Dining and Drinking > Restaurant
15014	Health and Medicine > Hospital
17039	Retail > Fashion Retail